apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
  labels:
    app: mysite
spec:
  replicas: 1
  selector:
  
  template:
    spec:
  volumes:
  - name: db
    persistentVolumeClaim:
        claimName: db
  containers:
  - name: mysite
    image: ghcr.io/cturtle98/cis-92:main
    imagePullPolicy: Always
    volumeMounts:
    - name: db
      mountPath: /db
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "postgres"

    - name: DB_NAME
      value: "mysitedb"

    - name: DB_USER
      value: "mysiteuser"

    - name: DB_HOST
      value: "postgres"

    - name: DB_PASSWORD
      value: "mysitepassword"

    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"

    - name: DJANGO_ADMIN_USERNAME
      value: "test"

    - name: DJANGO_SUPERUSER_PASSWORD
      value: "testtest"
      