apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    app: mysite
  
spec:
  containers:
  - name: postgres
    image: docker.io/postgres:14.2
    imagePullPolicy: Always
    volumeMounts:
    - name: postgres-pvc
      mountPath: /var/lib/postgresql/data
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      env:
      - name: POSTGRES_DB
        value: "mysitedb"
        
      - name: POSTGRES_USER
        value: "mysiteuser"

      - name: POSTGRES_PASSWORD
        value: "mysitepassword"